# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Add.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
import pymysql
conn = pymysql.connect(host = 'localhost', user = "root", password = "", database = "school")
cursor = conn.cursor()

class Add_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(465, 436)
        self.pushButton_back = QtWidgets.QPushButton(Dialog)
        self.pushButton_back.setGeometry(QtCore.QRect(340, 30, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(11)
        self.pushButton_back.setFont(font)
        self.pushButton_back.setObjectName("pushButton_back")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(20, 20, 291, 41))
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.tabWidget_ = QtWidgets.QTabWidget(Dialog)
        self.tabWidget_.setGeometry(QtCore.QRect(20, 80, 431, 341))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(11)
        self.tabWidget_.setFont(font)
        self.tabWidget_.setObjectName("tabWidget_")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setGeometry(QtCore.QRect(20, 25, 111, 21))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(9)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.lineEdit_id = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_id.setGeometry(QtCore.QRect(150, 20, 161, 31))
        self.lineEdit_id.setObjectName("lineEdit_id")
        self.pushButton_add = QtWidgets.QPushButton(self.tab)
        self.pushButton_add.setGeometry(QtCore.QRect(350, 260, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_add.setFont(font)
        self.pushButton_add.setObjectName("pushButton_add")
        self.lineEdit_name = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_name.setGeometry(QtCore.QRect(150, 70, 161, 31))
        self.lineEdit_name.setObjectName("lineEdit_name")
        self.label_4 = QtWidgets.QLabel(self.tab)
        self.label_4.setGeometry(QtCore.QRect(20, 70, 111, 21))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(9)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.tab)
        self.label_5.setGeometry(QtCore.QRect(20, 120, 111, 21))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(9)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.lineEdit_department = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_department.setGeometry(QtCore.QRect(150, 120, 161, 31))
        self.lineEdit_department.setObjectName("lineEdit_department")
        self.label_8 = QtWidgets.QLabel(self.tab)
        self.label_8.setGeometry(QtCore.QRect(20, 170, 111, 21))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(9)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.lineEdit_lab = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_lab.setGeometry(QtCore.QRect(150, 170, 161, 31))
        self.lineEdit_lab.setObjectName("lineEdit_lab")
        self.label_card_id = QtWidgets.QLabel(self.tab)
        self.label_card_id.setGeometry(QtCore.QRect(20, 220, 111, 21))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(9)
        self.label_card_id.setFont(font)
        self.label_card_id.setObjectName("label_card_id")
        self.lineEdit_cardID = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_cardID.setGeometry(QtCore.QRect(150, 220, 161, 31))
        self.lineEdit_cardID.setObjectName("lineEdit_cardID")
        self.lineEdit_password = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_password.setGeometry(QtCore.QRect(150, 265, 161, 31))
        self.lineEdit_password.setText("")
        self.lineEdit_password.setObjectName("lineEdit_password")
        self.label_3 = QtWidgets.QLabel(self.tab)
        self.label_3.setGeometry(QtCore.QRect(20, 270, 111, 21))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(9)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_students = QtWidgets.QLabel(self.tab)
        self.label_students.setGeometry(QtCore.QRect(330, 130, 72, 15))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(9)
        self.label_students.setFont(font)
        self.label_students.setText("")
        self.label_students.setObjectName("label_students")
        self.tabWidget_.addTab(self.tab, "")
        self.widget = QtWidgets.QWidget()
        self.widget.setObjectName("widget")
        self.label_9 = QtWidgets.QLabel(self.widget)
        self.label_9.setGeometry(QtCore.QRect(20, 70, 111, 21))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(9)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.widget)
        self.label_10.setGeometry(QtCore.QRect(20, 25, 111, 21))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(9)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.lineEdit_course_id = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_course_id.setGeometry(QtCore.QRect(150, 70, 161, 31))
        self.lineEdit_course_id.setObjectName("lineEdit_course_id")
        self.lineEdit_grades_std_id = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_grades_std_id.setGeometry(QtCore.QRect(150, 20, 161, 31))
        self.lineEdit_grades_std_id.setObjectName("lineEdit_grades_std_id")
        self.label_11 = QtWidgets.QLabel(self.widget)
        self.label_11.setGeometry(QtCore.QRect(20, 120, 111, 21))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(9)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.lineEdit_grades = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_grades.setGeometry(QtCore.QRect(150, 120, 161, 31))
        self.lineEdit_grades.setObjectName("lineEdit_grades")
        self.pushButton_add_2 = QtWidgets.QPushButton(self.widget)
        self.pushButton_add_2.setGeometry(QtCore.QRect(340, 210, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_add_2.setFont(font)
        self.pushButton_add_2.setObjectName("pushButton_add_2")
        self.label_grades = QtWidgets.QLabel(self.widget)
        self.label_grades.setGeometry(QtCore.QRect(160, 240, 72, 15))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(9)
        self.label_grades.setFont(font)
        self.label_grades.setText("")
        self.label_grades.setObjectName("label_grades")
        self.tabWidget_.addTab(self.widget, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.lineEdit_project_id = QtWidgets.QLineEdit(self.tab_3)
        self.lineEdit_project_id.setGeometry(QtCore.QRect(150, 75, 161, 31))
        self.lineEdit_project_id.setObjectName("lineEdit_project_id")
        self.label_12 = QtWidgets.QLabel(self.tab_3)
        self.label_12.setGeometry(QtCore.QRect(20, 75, 111, 21))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(9)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.lineEdit_project_std_id = QtWidgets.QLineEdit(self.tab_3)
        self.lineEdit_project_std_id.setGeometry(QtCore.QRect(150, 25, 161, 31))
        self.lineEdit_project_std_id.setObjectName("lineEdit_project_std_id")
        self.label_13 = QtWidgets.QLabel(self.tab_3)
        self.label_13.setGeometry(QtCore.QRect(20, 30, 111, 21))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(9)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.pushButton_add_3 = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_add_3.setGeometry(QtCore.QRect(350, 210, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_add_3.setFont(font)
        self.pushButton_add_3.setObjectName("pushButton_add_3")
        self.label_project = QtWidgets.QLabel(self.tab_3)
        self.label_project.setGeometry(QtCore.QRect(180, 220, 72, 15))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_project.setFont(font)
        self.label_project.setText("")
        self.label_project.setObjectName("label_project")
        self.tabWidget_.addTab(self.tab_3, "")

        self.pushButton_back.clicked.connect(Dialog.close)

        self.retranslateUi(Dialog)
        self.tabWidget_.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

        self.pushButton_add.clicked.connect(self.add_student)
        self.pushButton_add_2.clicked.connect(self.add_grades)
        self.pushButton_add_3.clicked.connect(self.add_project)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "数据添加"))
        self.pushButton_back.setText(_translate("Dialog", "返回"))
        self.label.setText(_translate("Dialog", "请选择需要添加的内容"))
        self.label_2.setText(_translate("Dialog", "请输入学号："))
        self.pushButton_add.setText(_translate("Dialog", "插入"))
        self.label_4.setText(_translate("Dialog", "请输入姓名："))
        self.label_5.setText(_translate("Dialog", "请输入院系号："))
        self.label_8.setText(_translate("Dialog", "请输入实验室号："))
        self.label_card_id.setText(_translate("Dialog", "请输入校园卡号："))
        self.label_3.setText(_translate("Dialog", "请输入密码："))
        self.tabWidget_.setTabText(self.tabWidget_.indexOf(self.tab), _translate("Dialog", "添加学生"))
        self.label_9.setText(_translate("Dialog", "请输入课程号："))
        self.label_10.setText(_translate("Dialog", "请输入学号："))
        self.label_11.setText(_translate("Dialog", "请输入分数："))
        self.pushButton_add_2.setText(_translate("Dialog", "插入"))
        self.tabWidget_.setTabText(self.tabWidget_.indexOf(self.widget), _translate("Dialog", "成绩录入"))
        self.label_12.setText(_translate("Dialog", "请输入项目号："))
        self.label_13.setText(_translate("Dialog", "请输入学号："))
        self.pushButton_add_3.setText(_translate("Dialog", "插入"))
        self.tabWidget_.setTabText(self.tabWidget_.indexOf(self.tab_3), _translate("Dialog", "加入项目组"))

    def add_project(self, Dialog):
        temp1 = self.lineEdit_project_std_id.text()
        temp2 = self.lineEdit_project_id.text()
        cursor.execute('set FOREIGN_KEY_CHECKS = 0')
        string = "insert into student_project(std_id, project_id) values('"+temp1+"','"+temp2+"')"
        try:
            cursor.execute(string)
            cursor.execute('set FOREIGN_KEY_CHECKS = 1')
            conn.commit()
            self.label_project.setText('加入项目组成功')
        except:
            self.label_project.setText('数据已存在')
            conn.rollback()

    def add_grades(self, Dialog):
        temp1 = self.lineEdit_grades_std_id.text()
        temp2 = self.lineEdit_course_id.text()
        temp3 = self.lineEdit_grades.text()
        string = "insert into student_course(std_id,course_id,grades) values('"+temp1+"','"+temp2+"',"+temp3+")"
        cursor.execute('set FOREIGN_KEY_CHECKS = 0')
        try:
            cursor.execute(string)
            cursor.execute('set FOREIGN_KEY_CHECKS = 1')
            conn.commit()
            self.label_grades.setText('成绩录入成功')
        except:
            self.label_grades.setText('数据已存在')
            conn.rollback()

    def add_student(self, Dialog):
        temp1 = self.lineEdit_id.text()
        temp2 = self.lineEdit_name.text()
        temp3 = self.lineEdit_department.text()
        temp4 = self.lineEdit_lab.text()
        temp5 = self.lineEdit_cardID.text()
        temp6 = self.lineEdit_password.text()
        string1 = "insert into card(card_id,std_id,password) values('"+temp5+"','"+temp1+"',"+temp6+")"
        string2 = "insert into student(std_id,lab_id,department_id,card_id,std_name) values('"
        string2 = string2+temp1+"','"+temp4+"','"+temp3+"','"+temp5+"','"+temp2+"')"
        cursor.execute('set FOREIGN_KEY_CHECKS = 0')
        try:
            cursor.execute(string1)
            cursor.execute(string2)
            cursor.execute('set FOREIGN_KEY_CHECKS = 1')
            conn.commit()
            self.label_students.setText('添加学生成功')
        except:
            self.label_students('学生信息已存在')
            conn.rollback()
        

