# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Change.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
import pymysql
conn = pymysql.connect(host = 'localhost', user = "root", password = "", database = "school")
cursor = conn.cursor()

class Change_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(465, 384)
        self.pushButton_back = QtWidgets.QPushButton(Dialog)
        self.pushButton_back.setGeometry(QtCore.QRect(340, 30, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(11)
        self.pushButton_back.setFont(font)
        self.pushButton_back.setObjectName("pushButton_back")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(20, 20, 291, 41))
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.tabWidget_ = QtWidgets.QTabWidget(Dialog)
        self.tabWidget_.setGeometry(QtCore.QRect(20, 80, 421, 291))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(11)
        self.tabWidget_.setFont(font)
        self.tabWidget_.setObjectName("tabWidget_")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.pushButton_change_depart = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_change_depart.setGeometry(QtCore.QRect(340, 210, 56, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_change_depart.setFont(font)
        self.pushButton_change_depart.setObjectName("pushButton_change_depart")
        self.label_3 = QtWidgets.QLabel(self.tab_2)
        self.label_3.setGeometry(QtCore.QRect(20, 15, 151, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.lineEdit_depart_std_id = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_depart_std_id.setGeometry(QtCore.QRect(180, 9, 131, 31))
        self.lineEdit_depart_std_id.setObjectName("lineEdit_depart_std_id")
        self.label_8 = QtWidgets.QLabel(self.tab_2)
        self.label_8.setGeometry(QtCore.QRect(20, 66, 151, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.lineEdit_department_id = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_department_id.setGeometry(QtCore.QRect(180, 60, 131, 31))
        self.lineEdit_department_id.setObjectName("lineEdit_department_id")
        self.label_2 = QtWidgets.QLabel(self.tab_2)
        self.label_2.setGeometry(QtCore.QRect(160, 180, 72, 15))
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label_10 = QtWidgets.QLabel(self.tab_2)
        self.label_10.setGeometry(QtCore.QRect(180, 200, 72, 15))
        self.label_10.setText("")
        self.label_10.setObjectName("label_10")
        self.tabWidget_.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.pushButton_change_card = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_change_card.setGeometry(QtCore.QRect(340, 210, 56, 31))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(9)
        self.pushButton_change_card.setFont(font)
        self.pushButton_change_card.setObjectName("pushButton_change_card")
        self.label_4 = QtWidgets.QLabel(self.tab_3)
        self.label_4.setGeometry(QtCore.QRect(20, 15, 131, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.lineEdit_card_std_id = QtWidgets.QLineEdit(self.tab_3)
        self.lineEdit_card_std_id.setGeometry(QtCore.QRect(170, 10, 141, 31))
        self.lineEdit_card_std_id.setObjectName("lineEdit_card_std_id")
        self.label_5 = QtWidgets.QLabel(self.tab_3)
        self.label_5.setGeometry(QtCore.QRect(20, 110, 131, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.lineEdit_password_2 = QtWidgets.QLineEdit(self.tab_3)
        self.lineEdit_password_2.setGeometry(QtCore.QRect(170, 105, 141, 31))
        self.lineEdit_password_2.setObjectName("lineEdit_password_2")
        self.label_6 = QtWidgets.QLabel(self.tab_3)
        self.label_6.setGeometry(QtCore.QRect(20, 160, 131, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.lineEdit_new_password = QtWidgets.QLineEdit(self.tab_3)
        self.lineEdit_new_password.setGeometry(QtCore.QRect(170, 155, 141, 31))
        self.lineEdit_new_password.setObjectName("lineEdit_new_password")
        self.label_7 = QtWidgets.QLabel(self.tab_3)
        self.label_7.setGeometry(QtCore.QRect(20, 65, 131, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.lineEdit_card_id_2 = QtWidgets.QLineEdit(self.tab_3)
        self.lineEdit_card_id_2.setGeometry(QtCore.QRect(170, 60, 141, 31))
        self.lineEdit_card_id_2.setObjectName("lineEdit_card_id_2")
        self.label_9 = QtWidgets.QLabel(self.tab_3)
        self.label_9.setGeometry(QtCore.QRect(140, 220, 72, 15))
        self.label_9.setText("")
        self.label_9.setObjectName("label_9")
        self.tabWidget_.addTab(self.tab_3, "")

        self.pushButton_back.clicked.connect(Dialog.close)

        self.retranslateUi(Dialog)
        self.tabWidget_.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

        self.pushButton_change_depart.clicked.connect(self.change_department)
        self.pushButton_change_card.clicked.connect(self.change_card)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "数据修改"))
        self.pushButton_back.setText(_translate("Dialog", "返回"))
        self.label.setText(_translate("Dialog", "请选择需要修改的内容"))
        self.pushButton_change_depart.setText(_translate("Dialog", "修改"))
        self.label_3.setText(_translate("Dialog", "请输入学号："))
        self.label_8.setText(_translate("Dialog", "请输入转入的系号："))
        self.tabWidget_.setTabText(self.tabWidget_.indexOf(self.tab_2), _translate("Dialog", "学生转系"))
        self.pushButton_change_card.setText(_translate("Dialog", "修改"))
        self.label_4.setText(_translate("Dialog", "请输入学号："))
        self.label_5.setText(_translate("Dialog", "请输入新的密码："))
        self.label_6.setText(_translate("Dialog", "请确认密码："))
        self.label_7.setText(_translate("Dialog", "请输入新的卡号："))
        self.tabWidget_.setTabText(self.tabWidget_.indexOf(self.tab_3), _translate("Dialog", "更换校园卡"))
    
    def change_department(self, Dialog):
        temp1 = self.lineEdit_depart_std_id.text()
        temp2 = self.lineEdit_department_id.text()
        string = "update student set student.department_id ='"+temp2+"'"
        string += " where student.std_id = '"+temp1+"'"
        cursor.execute(string)
        conn.commit()
        self.label_10.setText('转系成功')

    def change_card(self, Dialog):
        temp1 = self.lineEdit_card_std_id.text()
        temp2 = self.lineEdit_card_id_2.text()
        temp3 = self.lineEdit_password_2.text()
        temp4 = self.lineEdit_new_password.text()
        if temp3 == temp4:
            string1 = "update card set card_id = '"+temp2+"',password = '"+temp4+"' where card.std_id = '"+temp1+"'"
            string2 = "update student set card_id = '"+temp2+"' where student.std_id = '"+temp1+"'"
            cursor.execute('set FOREIGN_KEY_CHECKS = 0')
            cursor.execute(string1)
            cursor.execute(string2)
            cursor.execute('set FOREIGN_KEY_CHECKS = 1')
            conn.commit()
            self.label_9.setText('校园卡更换成功')
        else:
            self.label_9.setText('密码确认有误，请重新输入')
        

